version: '3.3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      # POSTGRES_PASSWORD: example
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - './volumes/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    volumes:
      - './volumes/pgadmin4/servers.json:/pgadmin4/servers.json'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4@pgadmin.org
      # PGADMIN_ENABLE_TLS: "true"
    ports:
      - '8080:80'
  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres@db/memes
      ENABLE_GRAPHQL_PLAYGROUND: 'true'
    ports:
      - '5000:5000'
