version: '3.3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      # POSTGRES_PASSWORD: example
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: pgadmin4@pgadmin.org
        # PGADMIN_ENABLE_TLS: "true"
    ports:
      - '8080:80'
  api:
    image: rosmem-backend
    ports:
      - '5000:80'